/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hangmangamefinalversion;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author aHafi
 */
public class MenuPage extends javax.swing.JFrame {

    /**
     * Creates new form MenuPage
     */
    
    public MenuPage() {
        
        initComponents();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        MinMax = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        MainArea = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        game = new javax.swing.JLabel();
        board = new javax.swing.JLabel();
        tutor = new javax.swing.JLabel();
        quit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(25, 29, 74));
        Header.setkEndColor(new java.awt.Color(15, 19, 75));
        Header.setkGradientFocus(700);
        Header.setkStartColor(new java.awt.Color(102, 0, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/1704309121377 (1).png"))); // NOI18N

        MinMax.setBackground(new java.awt.Color(25, 29, 84));
        MinMax.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(25, 29, 74));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete_32px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MinMax.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(25, 29, 74));

        back.setForeground(new java.awt.Color(102, 0, 0));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back_32px.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MinMax.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(622, Short.MAX_VALUE))
            .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                    .addGap(0, 650, Short.MAX_VALUE)
                    .addComponent(MinMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeaderLayout.createSequentialGroup()
                    .addComponent(MinMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        MainArea.setBackground(new java.awt.Color(25, 29, 74));
        MainArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new Color(0,0,0,0));
        jPanel3.setLayout(new java.awt.GridLayout(4, 1, 0, 10));
        jPanel3.setVisible(false);
        Timer ptimer = new Timer(1350,new ActionListener (){

            public void actionPerformed(ActionEvent e){
                jPanel3.setVisible(true);
            }
        });
        ptimer.setRepeats(false);
        ptimer.start();

        game.setForeground(new java.awt.Color(102, 0, 0));
        new Fonting(game,20);
        game.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        game.setText("Start Game");
        game.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gameMouseEntered(evt);
            }
        });
        jPanel3.add(game);

        board.setBackground(new Color(0,0,0,0));
        board.setForeground(new java.awt.Color(102, 0, 0));
        new Fonting(board);
        board.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        board.setText("Leaderboard");
        board.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boardMouseExited(evt);
            }
        });
        jPanel3.add(board);

        tutor.setBackground(new Color(0,0,0,0));
        tutor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tutor.setForeground(new java.awt.Color(102, 0, 0));
        new Fonting(tutor,20);
        tutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tutor.setText("Tutorial");
        tutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tutorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tutorMouseExited(evt);
            }
        });
        jPanel3.add(tutor);

        new Fonting(quit,24);
        quit.setForeground(new java.awt.Color(102, 0, 0));
        quit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quit.setText("Quit.");
        quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitMouseClicked(evt);
            }
        });
        jPanel3.add(quit);

        MainArea.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 210, 270));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/1705229327624_1.gif"))); // NOI18N
        Timer frameStopper = new Timer (1500, new ActionListener(){
            public void actionPerformed(ActionEvent e){
                new javax.swing.ImageIcon(getClass().getResource("/Icon/1705229327624_1.gif")).getImage().flush();
                new javax.swing.ImageIcon(getClass().getResource("/Icon/1705229327624_1.gif")).setImageObserver(null);
            }
        });
        frameStopper.setRepeats(false);
        frameStopper.start();
        MainArea.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        getContentPane().add(MainArea, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(800, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       public void Timing(javax.swing.JLabel label){
           Timer timer = new Timer(1500,new ActionListener (){

            public void actionPerformed(ActionEvent e){
                label.setVisible(true);
            }
        });
        timer.setRepeats(false);
        timer.start();
       }
       
public void changeColor(JPanel hover , Color rand){
    hover.setBackground(rand);
}
public void ChangeColor(javax.swing.JLabel hover , Color rand){
    hover.setBackground(new Color(0,0,0,0));
    hover.setForeground(rand);
    
}
    private void boardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardMouseEntered
        
    }//GEN-LAST:event_boardMouseEntered

    private void boardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardMouseExited
       
    }//GEN-LAST:event_boardMouseExited

    private void tutorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorMouseEntered
        
    }//GEN-LAST:event_tutorMouseEntered

    private void tutorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorMouseExited
       
    }//GEN-LAST:event_tutorMouseExited

    private void gameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameMouseClicked
       new Mode().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_gameMouseClicked

    private void gameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameMouseEntered
        
    }//GEN-LAST:event_gameMouseEntered

    private void boardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardMouseClicked
         new LeaderBoard().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_boardMouseClicked

    private void quitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitMouseClicked
        CustomButtonQuit customButtonExample = new CustomButtonQuit();

        // Call the main method to execute the dialog
        customButtonExample.main(null);
    }//GEN-LAST:event_quitMouseClicked

    private void tutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorMouseClicked
       new Toturial().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_tutorMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        CustomButtonQuit customButtonExample = new CustomButtonQuit();

        // Call the main method to execute the dialog
        customButtonExample.main(null);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        changeColor(close ,new Color(255,94,5));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        changeColor(close ,new Color(25,29,74));
    }//GEN-LAST:event_jLabel1MouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

        new MenuPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        changeColor(jPanel4 ,new Color(255,94,5));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        changeColor(jPanel4 ,new Color(25,29,74));
    }//GEN-LAST:event_backMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel Header;
    private javax.swing.JPanel MainArea;
    private javax.swing.JPanel MinMax;
    private javax.swing.JLabel back;
    private javax.swing.JLabel board;
    private javax.swing.JPanel close;
    private javax.swing.JLabel game;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel quit;
    private javax.swing.JLabel tutor;
    // End of variables declaration//GEN-END:variables
}
