/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hangmangamefinalversion;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author aHafi
 */
public class Toturial extends javax.swing.JFrame {

   private  boolean flag = true;
    public Toturial() {
        initComponents();
        showPanel(main);
    }
public void showPanel(JPanel panel){
    play.setVisible(false);
        hum.setVisible(false);
            Ai.setVisible(false);
            
            panel.setVisible(true);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        MinMax = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        MainPanel = new keeptoo.KGradientPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        max1 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        menu = new keeptoo.KGradientPanel();
        Play = new javax.swing.JLabel();
        Hum = new javax.swing.JLabel();
        AI = new javax.swing.JLabel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        banner = new javax.swing.JLabel();
        main = new keeptoo.KGradientPanel();
        hum = new keeptoo.KGradientPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Ai = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        play = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(25, 29, 74));
        Header.setkEndColor(new java.awt.Color(15, 19, 75));
        Header.setkGradientFocus(700);
        Header.setkStartColor(new java.awt.Color(102, 0, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/1704309121377 (1).png"))); // NOI18N

        MinMax.setBackground(new java.awt.Color(25, 29, 84));
        MinMax.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(25, 29, 74));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete_32px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MinMax.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(25, 29, 74));

        back.setForeground(new java.awt.Color(102, 0, 0));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back_32px.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MinMax.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(622, Short.MAX_VALUE))
            .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                    .addGap(0, 650, Short.MAX_VALUE)
                    .addComponent(MinMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeaderLayout.createSequentialGroup()
                    .addComponent(MinMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        MainPanel.setBackground(new java.awt.Color(25, 29, 74));
        MainPanel.setkEndColor(new java.awt.Color(15, 19, 75));
        MainPanel.setkGradientFocus(700);
        MainPanel.setkStartColor(new java.awt.Color(102, 0, 0));
        MainPanel.setLayout(new java.awt.BorderLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(25, 29, 74));
        kGradientPanel1.setkGradientFocus(700);
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 0, 0));
        kGradientPanel1.setLayout(new java.awt.BorderLayout());

        kGradientPanel2.setkStartColor(new java.awt.Color(25, 29, 74));
        kGradientPanel2.setMinimumSize(new java.awt.Dimension(50, 100));

        jPanel1.setBackground(new java.awt.Color(25, 29, 74));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        max1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        max1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/menu_32px.png"))); // NOI18N
        max1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                max1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                max1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                max1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(max1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(max1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 400, Short.MAX_VALUE))
        );

        kGradientPanel1.add(kGradientPanel2, java.awt.BorderLayout.LINE_START);

        kGradientPanel3.setkEndColor(new java.awt.Color(25, 29, 74));
        kGradientPanel3.setkGradientFocus(700);
        kGradientPanel3.setkStartColor(new java.awt.Color(102, 0, 0));
        kGradientPanel3.setLayout(new java.awt.BorderLayout());

        menu.setkEndColor(new java.awt.Color(102, 0, 0));
        menu.setkGradientFocus(10);
        menu.setkStartColor(new java.awt.Color(255, 0, 0));
        menu.setPreferredSize(new java.awt.Dimension(200, 450));

        new Fonting(Play,14);
        Play.setForeground(new java.awt.Color(51, 0, 0));
        Play.setText("How To Play Game");
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PlayMouseExited(evt);
            }
        });

        new Fonting(Hum,18);
        Hum.setForeground(new java.awt.Color(51, 0, 0));
        Hum.setText("vs Hum Mode");
        Hum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HumMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HumMouseExited(evt);
            }
        });

        new Fonting(AI,18);
        AI.setForeground(new java.awt.Color(51, 0, 0));
        AI.setText("vs AI Mode");
        AI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AIMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AIMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Play, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(Hum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Play, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Hum, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AI, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        kGradientPanel3.add(menu, java.awt.BorderLayout.LINE_START);

        kGradientPanel6.setkEndColor(new java.awt.Color(25, 29, 74));
        kGradientPanel6.setkGradientFocus(700);
        kGradientPanel6.setkStartColor(new java.awt.Color(102, 0, 0));
        kGradientPanel6.setLayout(new java.awt.BorderLayout());

        kGradientPanel4.setkEndColor(new java.awt.Color(25, 29, 74));
        kGradientPanel4.setkGradientFocus(700);
        kGradientPanel4.setkStartColor(new java.awt.Color(102, 0, 0));

        new Fonting(banner,24);
        banner.setText("Welcome...Lets Learn");
        banner.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(banner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        kGradientPanel6.add(kGradientPanel4, java.awt.BorderLayout.PAGE_START);

        main.setkEndColor(new java.awt.Color(25, 29, 74));
        main.setkGradientFocus(700);
        main.setkStartColor(new java.awt.Color(102, 0, 0));
        main.setLayout(new java.awt.BorderLayout());

        hum.setkEndColor(new java.awt.Color(25, 29, 74));
        hum.setkGradientFocus(700);
        hum.setkStartColor(new java.awt.Color(102, 0, 0));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("make sure to write same word in both fields");

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("words are not case sensitive ");

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Guess the word before skeleton to be drawn to in ");

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("One person challenge other by simply write the word in given fields");

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Lets challenge each other...");

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Vs Hum Mode is designed for Frienda to challenge each other");

        javax.swing.GroupLayout humLayout = new javax.swing.GroupLayout(hum);
        hum.setLayout(humLayout);
        humLayout.setHorizontalGroup(
            humLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(humLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(humLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        humLayout.setVerticalGroup(
            humLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(humLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        main.add(hum, java.awt.BorderLayout.PAGE_END);

        Ai.setkEndColor(new java.awt.Color(25, 29, 74));
        Ai.setkGradientFocus(700);
        Ai.setkStartColor(new java.awt.Color(102, 0, 0));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("In AI mode there are 3 Difficulties level");

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Hard: Harder and Lengthy words");

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Easy: Simpler and shorter kength words");

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Guess the word befor skeleton is completely drawn. else you lose");

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Play to win");

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Medium: Average and medium length words");

        javax.swing.GroupLayout AiLayout = new javax.swing.GroupLayout(Ai);
        Ai.setLayout(AiLayout);
        AiLayout.setHorizontalGroup(
            AiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                .addContainerGap())
        );
        AiLayout.setVerticalGroup(
            AiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        main.add(Ai, java.awt.BorderLayout.PAGE_START);

        play.setkEndColor(new java.awt.Color(102, 0, 0));
        play.setkGradientFocus(700);
        play.setkStartColor(new java.awt.Color(102, 0, 0));
        play.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("guess the word or the hangman figure is fully drawn.");
        play.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 530, 50));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("The goal of the Hangman game is to guess a hidden word before a stick hangman ");
        play.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, 530, 50));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText(" is completely drawn. The hidden word is represented by a row of dashes.");
        play.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 530, 50));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("If the guessed letter is in the hidden word, all instances of that letter are ");
        play.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 530, 50));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("in the word. If the guessed letter is not in the word, a part of the ");
        play.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 530, 50));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("hangman figure is drawn. The game continues until the players successfully ");
        play.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 530, 50));

        main.add(play, java.awt.BorderLayout.CENTER);

        kGradientPanel6.add(main, java.awt.BorderLayout.CENTER);

        kGradientPanel3.add(kGradientPanel6, java.awt.BorderLayout.CENTER);

        kGradientPanel1.add(kGradientPanel3, java.awt.BorderLayout.CENTER);

        MainPanel.add(kGradientPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(800, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        CustomButtonQuit customButtonExample = new CustomButtonQuit();

        // Call the main method to execute the dialog
        customButtonExample.main(null);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        changeColor(close ,new Color(255,94,5));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        changeColor(close ,new Color(25,29,74));
    }//GEN-LAST:event_jLabel1MouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

        new MenuPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        changeColor(jPanel4 ,new Color(255,94,5));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        changeColor(jPanel4 ,new Color(25,29,74));
    }//GEN-LAST:event_backMouseExited

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        changeColor(jPanel1 ,new Color(25,29,74));
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        changeColor(jPanel1 ,new Color(255,94,5));
    }//GEN-LAST:event_jPanel1MouseEntered

    private void max1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max1MouseExited
        changeColor(max1 ,new Color(25,29,74));
    }//GEN-LAST:event_max1MouseExited

    private void max1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max1MouseEntered
        changeColor(max1 ,new Color(255,94,5));
    }//GEN-LAST:event_max1MouseEntered

    private void max1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max1MouseClicked
        if(flag){
            menu.setVisible(false);
            flag  = false;
        }else{
            menu.setVisible(true);
            flag = true;
        }
    }//GEN-LAST:event_max1MouseClicked

    private void PlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseEntered
        Play.setForeground(new Color(255,94,5));
    }//GEN-LAST:event_PlayMouseEntered

    private void PlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseExited
        Play.setForeground(new Color(51,0,0));
    }//GEN-LAST:event_PlayMouseExited

    private void HumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HumMouseEntered
        Hum.setForeground(new Color(255,94,5));
    }//GEN-LAST:event_HumMouseEntered

    private void HumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HumMouseExited
       Hum.setForeground(new Color(51,0,0));;
    }//GEN-LAST:event_HumMouseExited

    private void HumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HumMouseClicked
        banner.setText("vs Hum");
        showPanel(hum);
    }//GEN-LAST:event_HumMouseClicked

    private void AIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AIMouseClicked
        banner.setText("vs AI");
        showPanel(Ai);
    }//GEN-LAST:event_AIMouseClicked

    private void AIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AIMouseEntered
       AI.setForeground(new Color(255,94,5));
    }//GEN-LAST:event_AIMouseEntered

    private void AIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AIMouseExited
        AI.setForeground(new Color(51,0,0));
    }//GEN-LAST:event_AIMouseExited

    private void PlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseClicked
        banner.setText("How to Play Game");
        showPanel(play);
        
    }//GEN-LAST:event_PlayMouseClicked
public void changeColor(JPanel hover , Color rand){
    hover.setBackground(rand);
}
public void changeColor(JLabel hover , Color rand){
    hover.setBackground(rand);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Toturial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AI;
    private keeptoo.KGradientPanel Ai;
    private keeptoo.KGradientPanel Header;
    private javax.swing.JLabel Hum;
    private keeptoo.KGradientPanel MainPanel;
    private javax.swing.JPanel MinMax;
    private javax.swing.JLabel Play;
    private javax.swing.JLabel back;
    private javax.swing.JLabel banner;
    private javax.swing.JPanel close;
    private keeptoo.KGradientPanel hum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel main;
    private javax.swing.JLabel max1;
    private keeptoo.KGradientPanel menu;
    private keeptoo.KGradientPanel play;
    // End of variables declaration//GEN-END:variables
}
